.onAttach <- function(libname, pkgname) {
  packageStartupMessage("version 0.1.0 ('one-skate').\nHave you loaded {brms}?")
}
utils::globalVariables(c(
  "a",
  "alpha",
  "b",
  "c1",
  "c2",
  "c1_mean",
  "c2_mean",
  "c1_sigma",
  "c2_sigma",
  "d13c",
  "dn",
  "dn_sigma",
  "max_alpha",
  "min_alpha",
  "n1",
  "n2",
  "n1_sigma",
  "n2_sigma",
  "normal",
  "sigma_lb",
  "sigma_ub",
  "tp_lb",
  "tp_ub",
  "uniform"
))
